/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 公开端点。只返回 readiness, 不暴露环境/路径/版本细节。
         *
         *     返回结构:
         *     - status: "ok" 或 "degraded"（任一 readiness 检查失败时降级）
         *     - checks: {db_writable, disk_writable, settings_valid} 子对象
         *
         *     readiness 语义（2026-06-27 P1-4 修复）:
         *     - 所有 checks 通过 → status="ok", HTTP 200
         *     - 任一 check 失败 → status="degraded", HTTP 503
         *     - K8s/systemd readiness probe 应判 HTTP status，不只判 status 字段
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户 */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 案例列表（T6.5） */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        /** 创建案例（T6.5） */
        post: operations["create_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 案例详情（T6.5） */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        /** 删除案例（T6.5） */
        delete: operations["delete_case_api_cases__case_id__delete"];
        options?: never;
        head?: never;
        /** 更新案例（T6.5） */
        patch: operations["update_case_api_cases__case_id__patch"];
        trace?: never;
    };
    "/api/cases/{case_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审核案例（T6.5） */
        post: operations["review_case_api_cases__case_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 案例列表（T6.5） */
        get: operations["list_cases_api_admin_cases_get"];
        put?: never;
        /** 创建案例（T6.5） */
        post: operations["create_case_api_admin_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 案例详情（T6.5） */
        get: operations["get_case_api_admin_cases__case_id__get"];
        put?: never;
        post?: never;
        /** 删除案例（T6.5） */
        delete: operations["delete_case_api_admin_cases__case_id__delete"];
        options?: never;
        head?: never;
        /** 更新案例（T6.5） */
        patch: operations["update_case_api_admin_cases__case_id__patch"];
        trace?: never;
    };
    "/api/admin/cases/{case_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审核案例（T6.5） */
        post: operations["review_case_api_admin_cases__case_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单列表（T6.4） */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /** 手工录入订单（T6.4） */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单导出（CSV，默认脱敏） */
        get: operations["export_orders_csv_api_orders_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单详情（T6.4） */
        get: operations["get_order_api_orders__order_id__get"];
        put?: never;
        post?: never;
        /** 订单删除 / 匿名化（T12/A-4） */
        delete: operations["delete_or_anonymize_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        /** 订单更新 / 状态流转 / 退款（T6.4） */
        patch: operations["patch_order_api_orders__order_id__patch"];
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单列表（T6.4） */
        get: operations["list_orders_api_admin_orders_get"];
        put?: never;
        /** 手工录入订单（T6.4） */
        post: operations["create_order_api_admin_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单导出（CSV，默认脱敏） */
        get: operations["export_orders_csv_api_admin_orders_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单详情（T6.4） */
        get: operations["get_order_api_admin_orders__order_id__get"];
        put?: never;
        post?: never;
        /** 订单删除 / 匿名化（T12/A-4） */
        delete: operations["delete_or_anonymize_order_api_admin_orders__order_id__delete"];
        options?: never;
        head?: never;
        /** 订单更新 / 状态流转 / 退款（T6.4） */
        patch: operations["patch_order_api_admin_orders__order_id__patch"];
        trace?: never;
    };
    "/api/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 仪表盘统计（T6.2）
         * @description 返回管理后台仪表盘完整 payload: summary(订单/用户/收入 + 今日/7d/30d 切片) + 6 态分布 + 来源分布 + 服务版本分布 + 今日/7d/30d 趋势序列 (日粒度, 0 填充)。
         */
        get: operations["get_dashboard_api_stats_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单维度统计（T6.2 真实聚合）
         * @description 订单维度统计:T6.1 阶段为占位,T6.2 接入真实 SQL 聚合。字段名保持 T6.1 stub 阶段不变,前端旧契约不破。
         */
        get: operations["get_order_stats_api_stats_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 仪表盘统计（T6.2）
         * @description 返回管理后台仪表盘完整 payload: summary(订单/用户/收入 + 今日/7d/30d 切片) + 6 态分布 + 来源分布 + 服务版本分布 + 今日/7d/30d 趋势序列 (日粒度, 0 填充)。
         */
        get: operations["get_dashboard_api_admin_stats_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单维度统计（T6.2 真实聚合）
         * @description 订单维度统计:T6.1 阶段为占位,T6.2 接入真实 SQL 聚合。字段名保持 T6.1 stub 阶段不变,前端旧契约不破。
         */
        get: operations["get_order_stats_api_admin_stats_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建正式分享链接 */
        post: operations["create_share_link_api_share_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-link/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询最近正式分享链接 */
        get: operations["latest_share_link_api_share_link_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-link/{code}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销正式分享链接 */
        post: operations["revoke_share_link_api_share_link__code__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 元数据枚举 */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表（T6.3） */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户详情（T6.3） */
        get: operations["get_user_detail_api_admin_users__user_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications/deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 删除申请列表 */
        get: operations["list_deletion_requests_api_admin_notifications_deletion_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications/ops-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运维告警列表 */
        get: operations["list_ops_alerts_api_admin_notifications_ops_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 通知审计列表 */
        get: operations["list_notifications_api_admin_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Public Order Endpoint */
        post: operations["create_public_order_endpoint_api_public_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/payments/mock/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock Payment Webhook */
        post: operations["mock_payment_webhook_api_public_payments_mock_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{token}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Order Attachment */
        post: operations["upload_order_attachment_portal__token__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{token}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Order Info */
        post: operations["submit_order_info_portal__token__info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{token}/deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Deletion Request */
        post: operations["submit_deletion_request_portal__token__deletion_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/share-link/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portal Latest Share Link */
        get: operations["portal_latest_share_link_portal_share_link_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portal Create Share Link */
        post: operations["portal_create_share_link_portal_share_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/share-link/{code}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portal Revoke Share Link */
        post: operations["portal_revoke_share_link_portal_share_link__code__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_order_attachment_portal__token__attachments_post */
        Body_upload_order_attachment_portal__token__attachments_post: {
            /** Files */
            files: string[];
        };
        /** CaseBasePayload */
        CaseBasePayload: {
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "success" | "typical" | "warning";
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** CaseDetailResponse */
        CaseDetailResponse: {
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "approved" | "rejected";
            /** Review Note */
            review_note?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "success" | "typical" | "warning";
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** CaseListResponse */
        CaseListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["CaseDetailResponse"][];
        };
        /** ConsentInfo */
        ConsentInfo: {
            /**
             * Consent Method
             * @enum {string}
             */
            consent_method: "verbal_chat" | "phone_recording" | "screenshot" | "written_form" | "self_declared";
            /** Consent Note */
            consent_note?: string | null;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /**
             * Source
             * @enum {string}
             */
            source: "xianyu" | "wechat" | "web" | "school";
            /** External Id */
            external_id?: string | null;
            /**
             * Service Version
             * @enum {string}
             */
            service_version: "audit" | "basic" | "standard" | "premium";
            /** Amount Cents */
            amount_cents: number;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Customer Wechat */
            customer_wechat?: string | null;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Candidate Id Card */
            candidate_id_card?: string | null;
            /** Candidate Province */
            candidate_province?: string | null;
            /** Candidate Score */
            candidate_score?: number | null;
            /** Candidate Rank */
            candidate_rank?: number | null;
            /** Candidate Subjects */
            candidate_subjects?: string[];
            /** Candidate Interests */
            candidate_interests?: string | null;
            /** Candidate Strong Subjects */
            candidate_strong_subjects?: string | null;
            /** Candidate Weak Subjects */
            candidate_weak_subjects?: string | null;
            /** Candidate Family */
            candidate_family?: string | null;
            /** Assigned Consultant */
            assigned_consultant?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            consent: components["schemas"]["ConsentInfo"];
        };
        /**
         * DashboardResponse
         * @description ``/api/stats/dashboard`` 响应契约。
         */
        DashboardResponse: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** By Status */
            by_status: {
                [key: string]: unknown;
            };
            /** By Source */
            by_source: {
                [key: string]: unknown;
            };
            /** By Service Version */
            by_service_version: {
                [key: string]: unknown;
            };
            /** Trends */
            trends: {
                [key: string]: unknown;
            };
            /** Generated At */
            generated_at: string;
        };
        /** DeletionRequestCreate */
        DeletionRequestCreate: {
            /** Requester Name */
            requester_name: string;
            /** Requester Contact */
            requester_contact: string;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "order_only" | "order_and_attachments" | "full_account";
            /** Confirm Guardian */
            confirm_guardian: boolean;
        };
        /** DeletionRequestCreated */
        DeletionRequestCreated: {
            /** Order Id */
            order_id: string;
            /** Request Logged */
            request_logged: boolean;
            /** Next Step */
            next_step: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakePayload */
        IntakePayload: {
            /**
             * Mode
             * @default submit
             * @enum {string}
             */
            mode: "draft" | "submit";
            /** Candidate Province */
            candidate_province?: string | null;
            /** Candidate Score */
            candidate_score?: number | null;
            /** Candidate Rank */
            candidate_rank?: number | null;
            /** Candidate Subjects */
            candidate_subjects?: string[];
            /** Candidate Interests */
            candidate_interests?: string | null;
            /** Target Cities */
            target_cities?: string[];
            /** Target Majors */
            target_majors?: string[];
            /** University Preferences */
            university_preferences?: string | null;
            /** School Region Preferences */
            school_region_preferences?: string[];
            /** School Preference Types */
            school_preference_types?: string[];
            /** Target Schools */
            target_schools?: string[];
            /** Disliked Majors */
            disliked_majors?: string[];
            /** Priority Strategy */
            priority_strategy?: string | null;
            /** Graduation Plan */
            graduation_plan?: string | null;
            /** Tuition Preference */
            tuition_preference?: string | null;
            /** Employment Region Preferences */
            employment_region_preferences?: string[];
            /** Family Background */
            family_background?: string | null;
            /** Industry Resources */
            industry_resources?: string | null;
            /** Extra Notes */
            extra_notes?: string | null;
            /** Interest Assessment Type */
            interest_assessment_type?: string | null;
            /** Interest Assessment Result */
            interest_assessment_result?: string | null;
            /** Interest Assessment Notes */
            interest_assessment_notes?: string | null;
            /** Existing Plan Summary */
            existing_plan_summary?: string | null;
            /** Guardian Notes */
            guardian_notes?: string | null;
            /** Consent Version */
            consent_version?: string | null;
            /** Consent Scope */
            consent_scope?: string | null;
            /**
             * Privacy Accepted
             * @default false
             */
            privacy_accepted: boolean;
            /**
             * Service Terms Accepted
             * @default false
             */
            service_terms_accepted: boolean;
            /**
             * Guardian Confirmed
             * @default false
             */
            guardian_confirmed: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** NotificationEventResponse */
        NotificationEventResponse: {
            /** Order Id */
            order_id: string;
            /** Event Type */
            event_type: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Last Attempt At */
            last_attempt_at?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Created At */
            created_at: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | string | null;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Items */
            items: components["schemas"]["NotificationEventResponse"][];
        };
        /** OpsAlertEventResponse */
        OpsAlertEventResponse: {
            /** Created At */
            created_at: string;
            /** Alert Type */
            alert_type: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** OpsAlertListResponse */
        OpsAlertListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["OpsAlertEventResponse"][];
        };
        /** OrderDeletionResponse */
        OrderDeletionResponse: {
            /** Action */
            action: string;
            /** Order Id */
            order_id: string;
            /**
             * Files Deleted
             * @default 0
             */
            files_deleted: number;
        };
        /** OrderDetailPayload */
        OrderDetailPayload: {
            /** Order */
            order: {
                [key: string]: unknown;
            };
            /** History */
            history: components["schemas"]["OrderHistoryItem"][];
            /** Available Next Statuses */
            available_next_statuses: string[];
        };
        /** OrderHistoryItem */
        OrderHistoryItem: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: string;
            /** From Status */
            from_status?: string | null;
            /** To Status */
            to_status: string;
            /** Actor */
            actor?: string | null;
            /** Reason */
            reason?: string | null;
            /** Changed At */
            changed_at: string;
        };
        /** OrderMutationResponse */
        OrderMutationResponse: {
            /** Order */
            order: {
                [key: string]: unknown;
            };
            /** History */
            history: components["schemas"]["OrderHistoryItem"][];
            /** Available Next Statuses */
            available_next_statuses: string[];
            /** Action */
            action: string;
        };
        /**
         * OrderStatsResponse
         * @description ``/api/stats/orders`` 响应契约 (沿用 T6.1 字段名,仅替换数据源)。
         */
        OrderStatsResponse: {
            /** Total Orders */
            total_orders: number;
            /** Total Revenue Cents */
            total_revenue_cents: number;
            /** By Status */
            by_status: {
                [key: string]: unknown;
            };
            /** By Source */
            by_source: {
                [key: string]: unknown;
            };
            /** By Service Version */
            by_service_version: {
                [key: string]: unknown;
            };
        };
        /** OrderSummaryResponse */
        OrderSummaryResponse: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** External Id */
            external_id?: string | null;
            /** Service Version */
            service_version: string;
            /** Status */
            status: string;
            /** Amount Cents */
            amount_cents: number;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Customer Wechat */
            customer_wechat?: string | null;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Candidate Province */
            candidate_province?: string | null;
            /** Assigned Consultant */
            assigned_consultant?: string | null;
            /** Intake Status */
            intake_status?: string | null;
            /** Intake Submitted At */
            intake_submitted_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Status Updated At */
            status_updated_at?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** PortalAttachmentUploaded */
        PortalAttachmentUploaded: {
            /** Order Id */
            order_id: string;
            /** Intake Status */
            intake_status: string;
            /** Stage */
            stage: string;
            /** Attachments */
            attachments: {
                [key: string]: unknown;
            }[];
        };
        /** PortalIntakeResponse */
        PortalIntakeResponse: {
            /** Intake Status */
            intake_status: string;
            /** Stage */
            stage: string;
            /** Order Id */
            order_id: string;
            /** Profile Minimum Complete */
            profile_minimum_complete: boolean;
            /** Profile Missing Fields */
            profile_missing_fields: string[];
        };
        /** PublicOrderCreate */
        PublicOrderCreate: {
            /**
             * Service Version
             * @enum {string}
             */
            service_version: "audit" | "basic" | "standard" | "premium";
            /** Amount Cents */
            amount_cents: number;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Customer Wechat */
            customer_wechat?: string | null;
            /** Customer Email */
            customer_email?: string | null;
            /** Candidate Name */
            candidate_name: string;
            /** Candidate Province */
            candidate_province?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PublicOrderCreated */
        PublicOrderCreated: {
            /** Order Id */
            order_id: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Service Version */
            service_version: string;
            /** Amount Cents */
            amount_cents: number;
            /** Next Step */
            next_step: string;
            /** Checkout Url */
            checkout_url: string;
            /** Portal Status Url */
            portal_status_url: string;
            /** Portal Info Url */
            portal_info_url: string;
        };
        /** ReviewCaseRequest */
        ReviewCaseRequest: {
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "approved" | "rejected";
            /** Review Note */
            review_note?: string | null;
        };
        /** UpdateOrderRequest */
        UpdateOrderRequest: {
            /** Updates */
            updates?: {
                [key: string]: unknown;
            } | null;
            /** To Status */
            to_status?: ("pending" | "paid" | "serving" | "delivered" | "completed" | "refunded") | null;
            /** Reason */
            reason?: string | null;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /** User Key */
            user_key: string;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Customer Wechat */
            customer_wechat?: string | null;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Candidate Province */
            candidate_province?: string | null;
            /** Order Count */
            order_count: number;
            /** Total Amount Cents */
            total_amount_cents: number;
            /** Latest Order At */
            latest_order_at?: string | null;
            /** Latest Status */
            latest_status?: string | null;
            /** Orders */
            orders: {
                [key: string]: unknown;
            }[];
        };
        /** UserListResponse */
        UserListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query?: string | null;
            /** Items */
            items: components["schemas"]["UserSummaryResponse"][];
        };
        /** UserPublic */
        UserPublic: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** UserSummaryResponse */
        UserSummaryResponse: {
            /** User Key */
            user_key: string;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Customer Wechat */
            customer_wechat?: string | null;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Candidate Province */
            candidate_province?: string | null;
            /** Order Count */
            order_count: number;
            /** Total Amount Cents */
            total_amount_cents: number;
            /** Latest Order At */
            latest_order_at?: string | null;
            /** Latest Status */
            latest_status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookAck */
        WebhookAck: {
            /** Payment Id */
            payment_id: string;
            /** Processed */
            processed: boolean;
            /** Idempotent */
            idempotent: boolean;
            /** Order Status */
            order_status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: ("success" | "typical" | "warning") | null;
                review_status?: ("pending" | "approved" | "rejected") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseBasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseBasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_case_api_cases__case_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_admin_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: ("success" | "typical" | "warning") | null;
                review_status?: ("pending" | "approved" | "rejected") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_admin_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseBasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_admin_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_admin_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_admin_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseBasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_case_api_admin_cases__case_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("pending" | "paid" | "serving" | "delivered" | "completed" | "refunded") | null;
                source?: ("xianyu" | "wechat" | "web" | "school") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_orders_csv_api_orders_export_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: ("pending" | "paid" | "serving" | "delivered" | "completed" | "refunded") | null;
                source?: ("xianyu" | "wechat" | "web" | "school") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_or_anonymize_order_api_orders__order_id__delete: {
        parameters: {
            query: {
                mode?: "delete" | "anonymize";
                reason: string;
            };
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_order_api_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_admin_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("pending" | "paid" | "serving" | "delivered" | "completed" | "refunded") | null;
                source?: ("xianyu" | "wechat" | "web" | "school") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_admin_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_orders_csv_api_admin_orders_export_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: ("pending" | "paid" | "serving" | "delivered" | "completed" | "refunded") | null;
                source?: ("xianyu" | "wechat" | "web" | "school") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_admin_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_or_anonymize_order_api_admin_orders__order_id__delete: {
        parameters: {
            query: {
                mode?: "delete" | "anonymize";
                reason: string;
            };
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_order_api_admin_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_stats_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    get_order_stats_api_stats_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatsResponse"];
                };
            };
        };
    };
    get_dashboard_api_admin_stats_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    get_order_stats_api_admin_stats_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatsResponse"];
                };
            };
        };
    };
    create_share_link_api_share_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_share_link_api_share_link_latest_get: {
        parameters: {
            query: {
                result_type: string;
                target_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_share_link_api_share_link__code__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description 姓名/手机号/微信/订单号搜索 */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_detail_api_admin_users__user_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deletion_requests_api_admin_notifications_deletion_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                order_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_alerts_api_admin_notifications_ops_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsAlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_admin_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                order_id?: string | null;
                status?: string | null;
                channel?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_public_order_endpoint_api_public_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicOrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrderCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mock_payment_webhook_api_public_payments_mock_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_order_attachment_portal__token__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_order_attachment_portal__token__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalAttachmentUploaded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_order_info_portal__token__info_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalIntakeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_deletion_request_portal__token__deletion_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionRequestCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_latest_share_link_portal_share_link_latest_get: {
        parameters: {
            query: {
                result_type: string;
                target_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_create_share_link_portal_share_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_revoke_share_link_portal_share_link__code__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
